name: EpgFilter

on:
  schedule:
    - cron: '0 0 * * *'

  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:

  runCode:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: EPG Filter

        run: |
          git config --global user.email "fbk@hll.localhost"
          git config --global user.name "fbk"
          git clone http://64.225.52.167:34400/xmltv/xteve.xml
          chmod +x exec_epgfilter.sh && ./exec_epgfilter.sh
          git add -A
          git commit -m "./epg_filter.xml is updated."
          git push
